trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@2
    inputs:
      version: '18.x'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies & build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '.'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/node-todo.zip'

  - publish: $(Build.ArtifactStagingDirectory)/node-todo.zip
    artifact: drop
